[Parameters]
segments = 9
bins = 5

[BaseFilter]
filterEnabled = 1
filterAzim = 1
filterRad = 1
filterZ = 1
maxAzim = 2.094395102
minAzim = -2.094395102
maxRad = 15.0
minRad = 0.4
maxZ = 0.2
minZ = -1.25

[GroundFilter]
mMax = 0.3639702342662
mSmall = 0.034920769
bMax = -0.6
bMin = -1.6
maxRmse = 0.002
dPrev = 0.1
dGround = 0.1

[Cluster]
;0->Hierarchical Clustering, 1->DBSCAN
clusteringMethod = 1
hierClusterDist = 0.0625
DBepsilon = 0.0625
DBminPts = 1

[Classifier]
ignoreClusterPointsLow = 5
ignoreClusterPointsHigh = 20000
reconstructCluster = 1
useOriginalClusterCircle = 1
r = 0.08
zMin = -0.3
zMax = 0.0
furtherReconstructDist = -0.86
regressCircleDiffThreshold = 0.00075
regressCircleMaxIter = 100
