[Parameters]
segments = 9
bins = 5

; First filter based on cylindrical coordinates
[BaseFilter]
filterEnabled = 1
filterAzim = 1
filterRad = 1
filterZ = 1
maxAzim = 1.570796327
minAzim = -1.570796327
maxRad = 15.0
minRad = 0.8
maxZ = 0.1
minZ = -1.5

[GroundFilter]
mMax = 0.3639702342662
mSmall = 0.034920769
bMax = -0.6
bMin = -1.6
maxRmse = 0.002
dPrev = 0.1
dGround = 0.18

[Cluster]
;0->Hierarchical Clustering, 1->DBSCAN, 2->HPDBSCAN
clusteringMethod = 2
;Distance parameters squared
hierClusterDist = 0.25
DBepsilon = 0.25
DBminPts = 2

[Classifier]
ignoreClusterPointsLow = 5
ignoreClusterPointsHigh = 7500
useCircleRegression = 1
useOriginalClusterForPos = 1
useAverageHeight = 1
usepRR = 1
r = 0.1
zMin = -0.4
zMax = 0.0
regressCircleDiffThreshold = 0.00075
regressCircleMaxIter = 100

; Settings for Ouster LiDAR
[Lidar]
hostIP = 10.5.5.1
lidarIP = 10.5.5.93
;1 -> 512x10, 2 -> 512x20, 3 -> 1024x10, 4 -> 1024x20, 5 -> 2048x10
lidarMode = 5
;1 -> TIME_FROM_INTERNAL_OSC, 2 -> TIME_FROM_SYNC_PULSE_IN, 3 -> TIME_FROM_PTP_1588
timestampMode = 3
;0 -> Don't receive and publish IMU data, 1 -> Receive and publish IMU data
imuMode = 0
publishRawPointcloud = 1
publishFilteredPcl = 1
invertXYMode = 0
runPipeline = 1
publishConesDetectedPointcloud = 0
lidar_origin_to_beam_origin = 0.012163
; Max number of non grounds points allowed to proceed with pointcloud processing
maxPointsProcessing = 15000
; Max time in ms of processing time allowed for each pointcloud
timeoutProcessing = 80
